### PR TITLE
Arabic input update.

### PR DESCRIPTION
**Pull request by EyadMahm0ud**
Note: Please review, some symbols have been replaced with some letters

### CODE REVIEW

**Comment by shinovon** [comment]
image

**Comment by vipaoL** [comment]
@shinovon

**Comment by shinovon** [comment]
When I try to move caret everything brokes

**Comment by shinovon** [comment]
[JTube.zip](https://github.com/shinovon/j2mekeyboard-library/files/11935344/JTube.zip)
Try it yourself

**Pull request closed without merging**
